### ISSUE TITLE
False dead code

### ISSUE THREAD

**Issue by Dangcaominh** [Liqi1003/lc3_vscode#1]
``As can be seen here
![image](https://github.com/user-attachments/assets/7cc8beda-be20-4e02-af98-4ff35806368e)
Most of my code is marked dead code and makes it very hard for me to write, but when I upload my code to this [https://lc3.cs.umanitoba.ca/](url) and run, it's clear that no part of my code is dead. Can the author fix it please or at least, add an option to choose whether or not to dim dead code.

Here's the source code

    .ORIG 0x3050

    LEA R0, INPUT_X
    PUTS

    GETC
    ST R0, STORE_R0

    LEA R0, INPUT_Y
    PUTS
    AND R0, R0, #0
    GETC
    ADD R1, R0, #0

    LEA R0, INPUT_Z
    PUTS

    GETC
    ADD R2, R0, #0
    LD R0, STORE_R0

    ; Hoàn thành nhập dữ liệu
    ; Chuyển dữ liệu ASCII sang số
    ; Lưu vào R0, R1, R2
    ; Đoạn code này optional, nếu bạn không muốn chuyển dữ liệu từ ASCII sang số thì bỏ qua

    ADD R3, R0, #0
    LD R4, ASCII_OFFSET
    JSR SUBTRACT
    ADD R0, R5, #0   ; R0 = R0 - ASCII_OFFSET

    ADD R3, R1, #0
    LD R4, ASCII_OFFSET
    JSR SUBTRACT
    ADD R1, R5, #0   ; R1 = R1 - ASCII_OFFSET

    ADD R3, R2, #0
    LD R4, ASCII_OFFSET
    JSR SUBTRACT
    ADD R2, R5, #0   ; R2 = R2 - ASCII_OFFSET

    ; Hoàn thành chuyển dữ liệu
    ; Tìm min, max

    ADD R6, R0, #0 ; R6 lưu min
    ADD R7, R0, #0 ; R7 lưu max

        ADD R3, R1, #0
        ADD R4, R6, #0
    JSR SUBTRACT        ; So sánh R1 và R6
        ADD R7, R7, #3
        ADD R5, R5, #0
    BRn MIN

        ADD R3, R2, #0
        ADD R4, R6, #0
    JSR SUBTRACT        ; So sánh R2 và R6
        ADD R7, R7, #3
        ADD R5, R5, #0
    BRn MIN

    ST R6, STORE_R6
    ADD R6, R0, #0

        ADD R3, R1, #0
        ADD R4, R6, #0
    JSR SUBTRACT        ; So sánh R1 và R6
        ADD R7, R7, #3
        ADD R5, R5, #0
    BRp MAX

        ADD R3, R2, #0
        ADD R4, R6, #0
    JSR SUBTRACT        ; So sánh R2 và R6
        ADD R7, R7, #3
        ADD R5, R5, #0
    BRp MAX

    ADD R7, R6, #0
    LD R6, STORE_R6

    ; Hoàn thành tìm min, max
    ; Hiển thị kết quả
        LD R0, ASCII_OFFSET
        ADD R0, R6, R0
    OUT
        LD R0, ASCII_OFFSET
        ADD R0, R7, R0
    OUT

    HALT

    ; Load sẵn dữ liệu vào R3 R4 trước khi gọi subroutine này
    ; Subroutine này trả về R5 = R3 - R4
    ; Subroutine này không khôi phục lại giá trị của R3, R4
    SUBTRACT
        NOT R4, R4
        ADD R4, R4, #1
        ADD R5, R3, R4
        RET
    MIN    
        ADD R6, R3, #0
        RET
    MAX 
        ADD R6, R3, #0
        RET
    STORE_R0 .BLKW 1
    STORE_R6 .BLKW 1
    INPUT_X .STRINGZ "Nhap X: \n"
    INPUT_Y .STRINGZ "Nhap Y: \n"
    INPUT_Z .STRINGZ "Nhap Z: \n"
    ASCII_OFFSET .FILL x30
    .END

**Comment by Liqi1003** [comment]
@Dangcaominh Thanks for bringing it up!
It looks like I developed this extension based on a version of LC-3 assembler that has slightly less variation in numbers.

I get the following error when assembling the given code:
```
STARTING PASS 1
  1: illegal operands for .ORIG
  3: instruction appears before .ORIG
2 errors found in first pass.
```

If you modify
```
.ORIG 0x3050
```
into
```
.ORIG x3050
```

I believe the unreachable code warning will disappear.

**Comment by Dangcaominh** [comment]
Wow it works, but there's also a small problem here
[image: image.png]
In my code, my SUBTRACT subroutine requires pre-loading values into R3 and
R4 and using them in it. But as can be seen here, the compiler is wrong
about this.

Vào Th 5, 29 thg 8, 2024 vào lúc 10:50 Li Qi ***@***.***>
đã viết:

**Comment by Dangcaominh** [comment]
Wow it works, but there's also a small problem here
![image](https://github.com/user-attachments/assets/2e0692f1-f6fc-44cf-867c-dc67e9f8db65)


In my code, my SUBTRACT subroutine requires pre-loading values into R3 and
R4 and using them in it. But as can be seen here, the compiler is wrong
about this.


In my code, my SUBTRACT subroutine requires pre-loading values into R3 and
R4 and using them in it. But as can be seen here, the compiler is wrong
about this.

**Comment by Liqi1003** [comment]
Yes, you are right. The subroutine analysis is not perfect and may have false positives. 

I have updated the code to add the setting to toggle whether to show dead code and unreachable codes (they are different, but both are shown as dim out). However, I have trouble accessing my VSCode marketplace account at this time, so might only be able to update the extension when I gain access to that account.

**Comment by Liqi1003** [comment]
The plugin has been updated. Now you have the option to turn off the check of unreachable code and dead code.
